#!/usr/bin/env python3
"""
make_run_file.py  —  generate a run file for all unique rational angles
between two bounds, for use with GNU parallel.

Usage:
    python make_run_file.py --t T --gates_path PATH --lo LO --hi HI [options]

Required:
    --t T               Value of t to pass to main.py
    --gates_path PATH   Path to the gates file
    --lo LO             Lower bound for angles (inclusive), as a float or fraction e.g. 0.25 or 1/4
    --hi HI             Upper bound for angles (inclusive), as a float or fraction e.g. 0.75 or 3/4

Optional:
    --max_denom N       Maximum denominator for rational angles [default: 120]
    --out FILE          Output run file name [default: run_angles.sh]
    --sorted            Sort angles in ascending order [default: shuffled,
                        which is better for parallel runs to avoid correlated load]

Example:
    python make_run_file.py --t 100 --gates_path BO.txt --lo 0.25 --hi 0.75
    python make_run_file.py --t 100 --gates_path BI.txt --lo 1/120 --hi 1 --max_denom 120 --sorted
"""

import argparse
import random
import sys
from fractions import Fraction


def parse_fraction(s):
    """Parse a string like '0.25', '1/4', or '0.333' into a Fraction."""
    try:
        if '/' in s:
            num, den = s.split('/')
            return Fraction(int(num), int(den))
        else:
            return Fraction(s).limit_denominator(10**9)
    except Exception:
        raise argparse.ArgumentTypeError(f"Cannot parse '{s}' as a fraction or float")


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--t',           required=True, type=int)
    p.add_argument('--gates_path',  required=True)
    p.add_argument('--lo',          required=True, type=parse_fraction,
                   help='Lower bound (inclusive), e.g. 0.25 or 1/4')
    p.add_argument('--hi',          required=True, type=parse_fraction,
                   help='Upper bound (inclusive), e.g. 0.75 or 3/4')
    p.add_argument('--max_denom',   default=120, type=int,
                   help='Maximum denominator [default: 120]')
    p.add_argument('--out',         default='run_angles.sh')
    p.add_argument('--sorted',      action='store_true',
                   help='Sort angles ascending (default: shuffled)')
    return p.parse_args()


def main():
    args = parse_args()

    lo = args.lo
    hi = args.hi

    if lo > hi:
        print(f"Error: --lo ({lo}) must be <= --hi ({hi})", file=sys.stderr)
        sys.exit(1)

    # Collect all unique rationals p/q with q <= max_denom and lo <= p/q <= hi
    fracs = set()
    for q in range(1, args.max_denom + 1):
        for p in range(0, q + 1):
            f = Fraction(p, q)
            if lo <= f <= hi:
                fracs.add(f)

    fracs = sorted(fracs)

    # Check for float collisions at 5 decimal places (the precision used in filenames)
    floats = [float(f) for f in fracs]
    rounded = [round(x, 5) for x in floats]
    if len(set(rounded)) != len(fracs):
        n_collisions = len(fracs) - len(set(rounded))
        print(f"Warning: {n_collisions} angle(s) round to the same 5-decimal filename. "
              f"Consider increasing --max_denom or the precision in dataStructures.py.",
              file=sys.stderr)

    print(f"Generated {len(fracs)} unique rational angles in [{lo}, {hi}] "
          f"with denominator <= {args.max_denom}", file=sys.stderr)

    if not args.sorted:
        random.shuffle(fracs)

    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by make_run_file.py",
        f"# t={args.t}  gates_path={args.gates_path}  "
        f"angles=[{lo}, {hi}]  max_denom={args.max_denom}",
        f"# Usage: parallel -j N < {args.out}",
        "",
    ]
    for f in fracs:
        lines.append(
            f"python main.py -n_of_generators 1 -d 2 -t {args.t} -sample_size 1 "
            f"-gates_path {args.gates_path} -fixed_gate_angle {float(f):.18f}"
        )

    with open(args.out, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')

    print(f"Written to: {args.out}", file=sys.stderr)


if __name__ == '__main__':
    main()
