#!/usr/bin/env bash
# find_missing_jobs.sh
#
# Scans groups/, extensions/, and group+extension/ to find all (group, extension, n)
# tuples where the output file is missing, then writes the needed python commands
# to a run file.
#
# Usage:
#   ./find_missing_jobs.sh {size}
#
# Example:
#   ./find_missing_jobs.sh 4
#
# Output:
#   run_missing.sh   — one python command per missing (group, extension) pair
#                      (gen_fast_ge.py handles all n=1..size internally, so one
#                       invocation per pair is enough; only written if ANY n is missing)

SIZE=${1}

if [ -z "${SIZE}" ]; then
    echo "Usage: $0 {size}"
    exit 1
fi

GROUPS_DIR="groups"
EXT_DIR="extensions"
OUT_DIR="group+extension"
RUN_FILE="run_missing.sh"

# Sanity checks
for dir in "${GROUPS_DIR}" "${EXT_DIR}"; do
    if [ ! -d "${dir}" ]; then
        echo "ERROR: directory '${dir}' not found."
        exit 1
    fi
done

mkdir -p "${OUT_DIR}"

echo "#!/usr/bin/env bash" > "${RUN_FILE}"
echo "# Auto-generated by find_missing_jobs.sh  (size=${SIZE})" >> "${RUN_FILE}"
echo "" >> "${RUN_FILE}"

missing_pairs=0
total_pairs=0

for group_path in "${GROUPS_DIR}"/*.npy; do
    [ -e "${group_path}" ] || { echo "No .npy files found in ${GROUPS_DIR}/"; exit 1; }

    # e.g. groups/clifford24.npy  ->  clifford24
    group_file=$(basename "${group_path}" .npy)

    for ext_path in "${EXT_DIR}"/*.npy; do
        [ -e "${ext_path}" ] || { echo "No .npy files found in ${EXT_DIR}/"; exit 1; }

        # e.g. extensions/diag_su2_0.0000_0.0314.npy  ->  diag_su2_0.0000_0.0314
        ext_file=$(basename "${ext_path}" .npy)

        total_pairs=$((total_pairs + 1))

        # Check whether ALL n=1..SIZE output files exist for this pair
        all_present=true
        missing_ns=()

        for n in $(seq 1 ${SIZE}); do
            out_file="${OUT_DIR}/${group_file}_${ext_file}_nt${n}.npy"
            if [ ! -f "${out_file}" ]; then
                all_present=false
                missing_ns+=("${n}")
            fi
        done

        if [ "${all_present}" = false ]; then
            missing_pairs=$((missing_pairs + 1))
            echo "# missing n=${missing_ns[*]} for ${group_file} + ${ext_file}" >> "${RUN_FILE}"
            echo "python gen_fast_ge.py ${group_path} ${ext_path} ${SIZE}" >> "${RUN_FILE}"
            echo "" >> "${RUN_FILE}"
        fi
    done
done

chmod +x "${RUN_FILE}"

echo "Checked ${total_pairs} (group, extension) pairs."
echo "Found ${missing_pairs} pairs with at least one missing output."
echo "Commands written to: ${RUN_FILE}"
