#!/usr/bin/env bash
# find_missing_norm.sh
#
# For every .npy file in full_sets/, checks whether the corresponding
# output file exists in norm_data/. Writes a python command for each
# missing one to run_missing_norm.sh.
#
# Usage:
#   ./find_missing_norm.sh

FULL_SETS_DIR="full_sets"
NORM_DATA_DIR="norm_data"
RUN_FILE="run_missing_norm.sh"

for dir in "${FULL_SETS_DIR}" "${NORM_DATA_DIR}"; do
    if [ ! -d "${dir}" ]; then
        echo "ERROR: directory '${dir}' not found."
        exit 1
    fi
done

echo "#!/usr/bin/env bash" > "${RUN_FILE}"
echo "# Auto-generated by find_missing_norm.sh" >> "${RUN_FILE}"
echo "" >> "${RUN_FILE}"

missing=0
total=0

for npy_path in "${FULL_SETS_DIR}"/*.npy; do
    [ -e "${npy_path}" ] || { echo "No .npy files found in ${FULL_SETS_DIR}/"; exit 1; }

    # e.g. full_sets/clifford24_diag_su2_0.0000_0.0952_upnt2.npy
    #   -> stem: clifford24_diag_su2_0.0000_0.0952_upnt2
    stem=$(basename "${npy_path}" .npy)

    total=$((total + 1))

    out_file="${NORM_DATA_DIR}/data_${stem}"

    if [ ! -f "${out_file}" ]; then
        missing=$((missing + 1))
        echo "python un_distance_integrator.py ${npy_path} > ${out_file}" >> "${RUN_FILE}"
    fi
done

chmod +x "${RUN_FILE}"

echo "Checked ${total} files in ${FULL_SETS_DIR}/."
echo "Found ${missing} missing outputs."
echo "Commands written to: ${RUN_FILE}"
