#!/usr/bin/env bash
# Auto-generated by find_missing_jobs.sh  (size=2)

# missing n=1 2 for BI + diag_su2_0.0000_0.0408
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0408.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0413
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0413.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0419
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0419.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0425
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0425.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0430
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0430.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0436
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0436.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0442
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0442.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0449
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0449.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0455
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0455.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0462
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0462.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0469
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0469.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0476
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0476.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0483
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0483.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0491
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0491.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0499
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0499.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0507
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0507.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0515
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0515.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0524
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0524.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0532
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0532.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0542
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0542.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0551
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0551.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0561
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0561.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0571
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0571.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0582
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0582.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0593
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0593.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0604
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0604.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0616
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0616.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0628
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0628.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0641
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0641.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0654
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0654.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0668
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0668.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0683
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0683.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0698
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0698.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0714
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0714.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0731
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0731.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0748
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0748.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0766
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0766.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0785
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0785.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0806
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0806.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0827
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0827.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0849
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0849.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0873
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0873.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0898
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0898.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0924
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0924.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0952
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0952.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.0982
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.0982.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1013
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1013.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1047
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1047.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1083
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1083.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1122
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1122.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1164
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1164.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1208
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1208.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1257
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1257.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1309
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1309.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1366
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1366.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1428
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1428.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1496
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1496.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1571
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1571.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1653
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1653.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1745
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1745.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1848
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1848.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.1963
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.1963.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.2094
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.2094.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.2244
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.2244.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.2417
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.2417.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.2618
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.2618.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.2856
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.2856.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.3142
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.3142.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.3491
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.3491.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.3927
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.3927.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.4488
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.4488.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.5236
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.5236.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.6283
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.6283.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_0.7854
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_0.7854.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_1.0472
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_1.0472.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_1.5708
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_1.5708.npy 2

# missing n=1 2 for BI + diag_su2_0.0000_3.1416
python gen_fast_ge.py groups/BI.npy extensions/diag_su2_0.0000_3.1416.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0262
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0262.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0264
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0264.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0266
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0266.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0269
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0269.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0271
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0271.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0273
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0273.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0276
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0276.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0278
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0278.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0280
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0280.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0283
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0283.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0286
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0286.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0288
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0288.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0291
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0291.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0294
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0294.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0296
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0296.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0299
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0299.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0302
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0302.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0305
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0305.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0308
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0308.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0311
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0311.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0314
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0314.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0317
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0317.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0321
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0321.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0324
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0324.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0327
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0327.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0331
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0331.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0334
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0334.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0338
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0338.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0341
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0341.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0345
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0345.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0349
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0349.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0353
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0353.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0357
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0357.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0361
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0361.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0365
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0365.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0370
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0370.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0374
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0374.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0379
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0379.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0383
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0383.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0388
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0388.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0393
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0393.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0398
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0398.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0403
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0403.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0408
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0408.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0413
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0413.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0419
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0419.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0425
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0425.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0430
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0430.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0436
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0436.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0442
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0442.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0449
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0449.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0455
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0455.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0462
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0462.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0469
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0469.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0476
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0476.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0483
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0483.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0491
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0491.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0499
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0499.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0507
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0507.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0515
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0515.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0524
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0524.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0532
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0532.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0542
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0542.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0551
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0551.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0561
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0561.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0571
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0571.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0582
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0582.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0593
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0593.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0604
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0604.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0616
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0616.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0628
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0628.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0641
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0641.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0654
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0654.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0668
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0668.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0683
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0683.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0698
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0698.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0714
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0714.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0731
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0731.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0748
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0748.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0766
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0766.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0785
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0785.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0806
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0806.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0827
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0827.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0849
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0849.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0873
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0873.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0898
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0898.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0924
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0924.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0952
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0952.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.0982
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.0982.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1013
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1013.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1047
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1047.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1083
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1083.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1122
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1122.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1164
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1164.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1208
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1208.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1257
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1257.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1309
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1309.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1366
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1366.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1428
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1428.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1496
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1496.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1571
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1571.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1653
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1653.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1745
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1745.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1848
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1848.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.1963
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.1963.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.2094
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.2094.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.2244
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.2244.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.2417
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.2417.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.2618
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.2618.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.2856
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.2856.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.3142
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.3142.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.3491
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.3491.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.3927
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.3927.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.4488
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.4488.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.5236
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.5236.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.6283
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.6283.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_0.7854
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_0.7854.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_1.0472
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_1.0472.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_1.5708
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_1.5708.npy 2

# missing n=1 2 for BO + diag_su2_0.0000_3.1416
python gen_fast_ge.py groups/BO.npy extensions/diag_su2_0.0000_3.1416.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0262
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0262.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0264
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0264.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0266
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0266.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0269
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0269.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0271
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0271.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0273
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0273.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0276
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0276.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0278
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0278.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0280
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0280.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0283
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0283.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0286
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0286.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0288
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0288.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0291
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0291.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0294
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0294.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0296
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0296.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0299
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0299.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0302
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0302.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0305
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0305.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0308
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0308.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0311
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0311.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0314
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0314.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0317
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0317.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0321
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0321.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0324
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0324.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0327
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0327.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0331
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0331.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0334
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0334.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0338
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0338.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0341
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0341.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0345
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0345.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0349
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0349.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0353
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0353.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0357
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0357.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0361
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0361.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0365
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0365.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0370
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0370.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0374
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0374.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0379
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0379.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0383
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0383.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0388
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0388.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0393
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0393.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0398
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0398.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0403
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0403.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0408
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0408.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0413
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0413.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0419
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0419.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0425
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0425.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0430
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0430.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0436
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0436.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0442
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0442.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0449
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0449.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0455
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0455.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0462
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0462.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0469
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0469.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0476
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0476.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0483
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0483.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0491
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0491.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0499
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0499.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0507
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0507.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0515
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0515.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0524
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0524.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0532
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0532.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0542
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0542.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0551
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0551.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0561
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0561.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0571
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0571.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0582
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0582.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0593
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0593.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0604
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0604.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0616
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0616.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0628
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0628.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0641
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0641.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0654
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0654.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0668
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0668.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0683
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0683.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0698
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0698.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0714
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0714.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0731
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0731.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0748
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0748.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0766
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0766.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0785
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0785.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0806
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0806.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0827
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0827.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0849
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0849.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0873
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0873.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0898
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0898.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0924
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0924.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0952
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0952.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.0982
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.0982.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1013
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1013.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1047
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1047.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1083
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1083.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1122
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1122.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1164
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1164.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1208
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1208.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1257
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1257.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1309
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1309.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1366
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1366.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1428
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1428.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1496
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1496.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1571
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1571.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1653
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1653.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1745
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1745.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1848
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1848.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.1963
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.1963.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.2094
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.2094.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.2244
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.2244.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.2417
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.2417.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.2618
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.2618.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.2856
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.2856.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.3142
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.3142.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.3491
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.3491.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.3927
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.3927.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.4488
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.4488.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.5236
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.5236.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.6283
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.6283.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_0.7854
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_0.7854.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_1.0472
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_1.0472.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_1.5708
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_1.5708.npy 2

# missing n=1 2 for BT + diag_su2_0.0000_3.1416
python gen_fast_ge.py groups/BT.npy extensions/diag_su2_0.0000_3.1416.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0262
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0262.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0264
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0264.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0266
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0266.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0269
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0269.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0271
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0271.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0273
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0273.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0276
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0276.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0278
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0278.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0280
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0280.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0283
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0283.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0286
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0286.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0288
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0288.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0291
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0291.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0294
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0294.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0296
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0296.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0299
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0299.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0302
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0302.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0305
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0305.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0308
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0308.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0311
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0311.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0314
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0314.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0317
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0317.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0321
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0321.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0324
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0324.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0327
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0327.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0331
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0331.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0334
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0334.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0338
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0338.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0341
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0341.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0345
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0345.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0349
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0349.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0353
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0353.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0357
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0357.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0361
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0361.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0365
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0365.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0370
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0370.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0374
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0374.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0379
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0379.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0383
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0383.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0388
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0388.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0393
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0393.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0398
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0398.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0403
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0403.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0408
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0408.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0413
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0413.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0419
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0419.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0425
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0425.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0430
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0430.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0436
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0436.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0442
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0442.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0449
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0449.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0455
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0455.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0462
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0462.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0469
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0469.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0476
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0476.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0483
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0483.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0491
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0491.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0499
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0499.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0507
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0507.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0515
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0515.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0524
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0524.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0532
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0532.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0542
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0542.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0551
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0551.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0561
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0561.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0571
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0571.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0582
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0582.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0593
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0593.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0604
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0604.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0616
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0616.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0628
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0628.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0641
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0641.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0654
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0654.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0668
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0668.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0683
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0683.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0698
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0698.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0714
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0714.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0731
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0731.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0748
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0748.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0766
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0766.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0785
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0785.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0806
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0806.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0827
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0827.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0849
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0849.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0873
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0873.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0898
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0898.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0924
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0924.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0952
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0952.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.0982
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.0982.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1013
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1013.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1047
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1047.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1083
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1083.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1122
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1122.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1164
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1164.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1208
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1208.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1257
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1257.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1309
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1309.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1366
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1366.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1428
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1428.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1496
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1496.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1571
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1571.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1653
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1653.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1745
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1745.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1848
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1848.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.1963
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.1963.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.2094
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.2094.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.2244
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.2244.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.2417
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.2417.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.2618
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.2618.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.2856
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.2856.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.3142
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.3142.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.3491
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.3491.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.3927
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.3927.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.4488
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.4488.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.5236
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.5236.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.6283
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.6283.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_0.7854
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_0.7854.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_1.0472
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_1.0472.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_1.5708
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_1.5708.npy 2

# missing n=1 2 for clifford192 + diag_su2_0.0000_3.1416
python gen_fast_ge.py groups/clifford192.npy extensions/diag_su2_0.0000_3.1416.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0262
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0262.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0264
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0264.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0266
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0266.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0269
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0269.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0271
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0271.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0273
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0273.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0276
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0276.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0278
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0278.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0280
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0280.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0283
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0283.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0286
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0286.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0288
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0288.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0291
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0291.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0294
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0294.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0296
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0296.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0299
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0299.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0302
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0302.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0305
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0305.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0308
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0308.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0311
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0311.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0314
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0314.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0317
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0317.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0321
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0321.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0324
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0324.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0327
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0327.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0331
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0331.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0334
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0334.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0338
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0338.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0341
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0341.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0345
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0345.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0349
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0349.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0353
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0353.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0357
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0357.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0361
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0361.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0365
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0365.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0370
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0370.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0374
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0374.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0379
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0379.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0383
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0383.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0388
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0388.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0393
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0393.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0398
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0398.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0403
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0403.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0408
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0408.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0413
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0413.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0419
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0419.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0425
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0425.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0430
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0430.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0436
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0436.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0442
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0442.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0449
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0449.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0455
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0455.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0462
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0462.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0469
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0469.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0476
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0476.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0483
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0483.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0491
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0491.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0499
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0499.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0507
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0507.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0515
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0515.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0524
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0524.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0532
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0532.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0542
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0542.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0551
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0551.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0561
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0561.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0571
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0571.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0582
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0582.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0593
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0593.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0604
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0604.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0616
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0616.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0628
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0628.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0641
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0641.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0654
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0654.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0668
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0668.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0683
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0683.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0698
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0698.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0714
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0714.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0731
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0731.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0748
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0748.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0766
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0766.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0785
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0785.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0806
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0806.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0827
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0827.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0849
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0849.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0873
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0873.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0898
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0898.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0924
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0924.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0952
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0952.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.0982
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.0982.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1013
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1013.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1047
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1047.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1083
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1083.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1122
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1122.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1164
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1164.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1208
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1208.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1257
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1257.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1309
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1309.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1366
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1366.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1428
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1428.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1496
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1496.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1571
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1571.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1653
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1653.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1745
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1745.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1848
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1848.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.1963
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.1963.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.2094
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.2094.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.2244
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.2244.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.2417
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.2417.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.2618
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.2618.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.2856
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.2856.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.3142
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.3142.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.3491
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.3491.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.3927
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.3927.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.4488
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.4488.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.5236
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.5236.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.6283
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.6283.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_0.7854
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_0.7854.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_1.0472
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_1.0472.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_1.5708
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_1.5708.npy 2

# missing n=1 2 for clifford24 + diag_su2_0.0000_3.1416
python gen_fast_ge.py groups/clifford24.npy extensions/diag_su2_0.0000_3.1416.npy 2

