"""
Generate the single-qubit Clifford group and write it to a text file
in the format expected by qco's get_gates_from_file():

    Line 0:      dimension n (= 2)
    Lines 1..:   one row of the matrix per line, space-separated complex
                 numbers, n rows per gate.

The Clifford group C < U(2) has 24 elements and is generated by
(equation 18 of arXiv:2505.00683):

    A = [[1, 0], [0, i]]          (phase gate S, order 4)
    B = [[1, 1], [-1, 1]] / sqrt2 (related to Hadamard, order 8)

both normalised to SU(2) by dividing by det^{1/2}.

Usage:
    python generate_clifford.py [output_path]

Defaults to writing  clifford.txt  in the current directory.
"""

import sys
import numpy as np
from itertools import product as iproduct

EPS = 1e-10
OUTPUT = sys.argv[1] if len(sys.argv) > 1 else "clifford.txt"


# ---------------------------------------------------------------------------
# Generators from the paper (eq. 18), normalised to SU(2)
# ---------------------------------------------------------------------------

def to_su2(M):
    """Divide a U(2) matrix by det^{1/2} to land in SU(2)."""
    M = np.array(M, dtype=complex)
    return M / (np.linalg.det(M) ** 0.5)


A_raw = np.array([[1, 0],
                  [0, 1j]], dtype=complex)

B_raw = np.array([[1,  1],
                  [-1, 1]], dtype=complex) / np.sqrt(2)

A = to_su2(A_raw)
B = to_su2(B_raw)


# ---------------------------------------------------------------------------
# Expand generators to full group by BFS (same algorithm as generate_group.py)
# ---------------------------------------------------------------------------

def is_proportional(X, Y):
    """True if X and Y are equal up to a global phase."""
    if np.all(np.abs(X) < EPS) or np.all(np.abs(Y) < EPS):
        return True
    # find a non-zero entry in X and compute the phase ratio
    for idx in iproduct(*[range(s) for s in X.shape]):
        if np.abs(X[idx]) > EPS:
            factor = Y[idx] / X[idx]
            break
    return np.all(np.abs(X * factor - Y) < EPS)


def group_from_generators(generators):
    from collections import deque
    n = generators[0].shape[0]
    group = [np.eye(n, dtype=complex)]
    queue = deque(generators)
    while queue:
        g = queue.popleft()
        for h in group:
            gh = g @ h
            if not any(is_proportional(gh, x) for x in group):
                group.append(gh)
                queue.append(gh)
    return group


# ---------------------------------------------------------------------------
# Build the group
# ---------------------------------------------------------------------------

print("Generating Clifford group from generators A and B ...")
clifford = group_from_generators([A, B])
print(f"  Found {len(clifford)} elements  (expected 24)")

# Sanity checks
dets = [np.linalg.det(g) for g in clifford]
det_errors = [abs(abs(d) - 1.0) for d in dets]
print(f"  Max |det| deviation from 1:  {max(det_errors):.2e}")
unitary_errors = [np.max(np.abs(g @ g.conj().T - np.eye(2))) for g in clifford]
print(f"  Max unitarity error:         {max(unitary_errors):.2e}")


# ---------------------------------------------------------------------------
# Write output file
# ---------------------------------------------------------------------------

def fmt_complex(z):
    """Write a complex number that Python's complex() can parse back.
    Format: a+bj or a-bj, no parentheses, sign explicit on imaginary part."""
    r, i = z.real, z.imag
    sign = '+' if i >= 0 else '-'
    return f"{r:.17g}{sign}{abs(i):.17g}j"


with open(OUTPUT, 'w') as f:
    f.write("2\n")
    for gate in clifford:
        for row in gate:
            f.write(" ".join(fmt_complex(x) for x in row) + "\n")

print(f"  Written to: {OUTPUT}")
